### ISSUE TITLE
For architecture arm64

### ISSUE THREAD

**Issue by SuCong** [core-plot/core-plot#449] opened 2021-07-15 09:36 UTC
In libcurl-ios-dist/lib/libcurl.a(libcurl_la-file.o), building for iOS Simulator, but linking in object file built for iOS, file 'libcurl-ios-dist/lib/libcurl.a' for architecture arm64

Xcode:12.5.1
Simulator: 14.5

Any help would be appreciated :)
Thanks in advance

**Comment by eskroch** [comment] 2021-07-15 22:50
Duplicate of #448

**Closed by eskroch** 2021-07-15 22:50 UTC
Labels: Duplicate
