### ISSUE TITLE
Coreplot 2.2 in cocoapods

### ISSUE THREAD

**Issue by declareerror** [core-plot/core-plot#306] opened 2016-09-16 02:46 UTC
Could you please update core plot 2.2 in cocoapods.org. because there is  Xcode7 issue  that you already fixed in branch 2.2

**Comment by eskroch** [comment] 2016-09-16 10:49
Duplicate of issue #302.

Core Plot 2.2 will be out soon. Watch [Twitter](https://twitter.com/coreplot) or the [discussion board](https://groups.google.com/forum/#!forum/coreplot-discuss) for the announcement. We'll post the release to Cocoapods as part of the release process.

**Closed by eskroch** 2016-09-16 10:49 UTC
Labels: Duplicate
