### ISSUE TITLE
Cocoapods warnings caused by CorePlot

### ISSUE THREAD

**Issue by Misantrofia** [core-plot/core-plot#401] opened 2019-03-19 16:21 UTC
I get this kind of warnings, for each target config, in the console when doing pod install
"The `Target [Debug]` target overrides the `ALWAYS_SEARCH_USER_PATHS` build setting defined in `../Pods/Target Support Files/Pods-Target/Pods-Target.debug.xcconfig'. This can lead to problems with the CocoaPods installation"
I tracked this down to CorePlot. If i remove the dependencies the warnings disappear. 

It is caused by this line in the podspec
"  s.xcconfig      = { 'ALWAYS_SEARCH_USER_PATHS' => 'YES' }". Even if I change this to NO, like it is in the other pods that I have and also in the main project it still shows the warnings. 
If I remove this line the warnings are gone.

Since this is an old config and is deprecated for a long time in Xcode I think it can be removed. 
Do you see any concerns if this config is removed ? 

I can submit a pull request with this change.

**Comment by nondescript74** [comment] 2019-03-19 16:36
You can change this in your project itself so you don't have to modify CorePlot.  If you search for "ALWAYS_SEARH_USER_PATHS", you can modify it to no.  Hope this helps.  I overcome it this way.

![Screen Shot 2019-03-19 at 10 36 02](https://user-images.githubusercontent.com/11380776/54624334-cbd40200-4a32-11e9-986a-880852f0250a.png)

**Comment by Misantrofia** [comment] 2019-03-19 17:01
I already have this set to NO in my project on all targets, but this doesn't clear the console warnings. 
![console_output](https://user-images.githubusercontent.com/5553140/54626236-6fe09c00-4a79-11e9-839b-b9b4d7114bc1.png)

**Comment by eskroch** [comment] 2019-12-31 15:19
Duplicate of issue #320. Fixed on the `release-2.3` branch.

**Closed by eskroch** 2019-12-31 15:19 UTC
Labels: Bug, Duplicate, Priority-Low
