### ISSUE TITLE
Text not drawing on OS X 10.11 (El Capitan)

### ISSUE THREAD

**Issue by Sully73** [core-plot/core-plot#210] opened 2015-07-20 23:07 UTC
I just installed the latest Beta for 10.11 and noticed that the text for all the core-plot graphs aren't appearing . Initially I though this may be related to issue #167 , but my app (including dependencies) do not use the stylemask
```objc
NSFullSizeContentViewWindowMask
```
Any thoughts on what else could be causing this? Has anyone else tested 10.11?  I'm currently using coreplot 1.6

Thanks

**Comment by eskroch** [comment] 2015-07-21 01:39
I don't have access to 10.11 for testing yet. Any troubleshooting you can do would be a big help in fixing this.

**Comment by Sully73** [comment] 2015-07-21 11:57
Sure I will see what I can come up with.

**Comment by grng** [comment] 2015-08-02 23:13
I encountered the similar problem in my project on OS X 10.10 (Mavericks).

All the plot labels are not drawn on the initial app load when I'm using NSVisualEffectView in the view hierarchy.

When I'm setting up the whole plot in `awakeFromNib`, `viewDidLoad` or first `viewWillAppear` calls, there're no labels on my app start. But setup in `viewDidAppear` always works.

If I go into another tab of my app and then return back, then labels appear when I re-setup a plot in `viewWillAppear` call.

There're no issues for any other screens, the bug happens only on the first screen that's visible immediately after the app's launch.

I wasn't able to reproduce it in a test project, sorry. It works for a small OS X app without issues.

But the main ideas are:
* plot appears as soon as app's window initially loaded
* plot is created in `awakeFromNib`, `viewDidLoad` or first `viewWillAppear`
* plot is inside NSVisualEffectView hierarchy

Workaround: use `viewWillAppear` if possible.

**Comment by kepowell** [comment] 2015-08-27 18:33
I am having the same problem with text on El Capitan.  I haven't had a chance to debug the code but an observation that might give some ideas.  When running the CPTTestApp the vertical zoom causes the tick numbers to appear and the horizontal zoom out causes the numbers that were outside the previous view to appear.  If you then move the graph around any numbers that get moved outside the view disappear until re-zooming.  It seems to me that this means that once a text item is masked out for any reason that it is not drawn on refreshes.

**Comment by tvlc** [comment] 2015-09-14 14:14
Same issues with 10.11 El Capitan GM Candidate. Any progress and fix planned for 1.6 release?

**Comment by Dirk-** [comment] 2015-09-14 17:20
I see this too. The version of my app which uses Core Plot 1.6 does not display any text on 10.11 GM (runs fine on 10.10.5), the former version which uses Core Plot 1.5.1 does display the text. I only switched from 1.5.1 to 1.6 the day before yesterday and did not change my plotting code.

**Comment by eskroch** [comment] 2015-09-14 23:50
@tvlc Not for version 1.x, but this issue is the last showstopper holding up release 2.0.

**Comment by vrbaski** [comment] 2015-09-15 01:24
The following change works for me:
I set the current graphics context (CPTTextStylePlatformSpecific.m) to a context passed to the drawInRect.
I had to clear it at the end or I was getting exceptions later. I'm not sure if that is a good fix, but it works for me.

-(void)drawInRect:(CGRect)rect withTextStyle:(CPTTextStyle *)style inContext:(CGContextRef)context
{
    if ( style.color == nil ) {
        return;
    }

    CGColorRef textColor = style.color.cgColor;
    
    BOOL currenContextIsNIL = NO;
    NSGraphicsContext *currentContext = [NSGraphicsContext currentContext];
    if(currentContext ==nil)
    {
        [NSGraphicsContext setCurrentContext:[NSGraphicsContext graphicsContextWithGraphicsPort:context flipped:NO]];
        currenContextIsNIL = YES;
    }

    CGContextSetStrokeColorWithColor(context, textColor);
    CGContextSetFillColorWithColor(context, textColor);

    CPTPushCGContext(context);

    NSFont *theFont    = nil;
    NSString *fontName = style.fontName;

    if ( fontName ) {
        theFont = [NSFont fontWithName:fontName size:style.fontSize];
    }

    if ( theFont ) {
        NSColor *foregroundColor                = style.color.nsColor;
        NSMutableParagraphStyle *paragraphStyle = [[NSMutableParagraphStyle alloc] init];
        paragraphStyle.alignment     = (NSTextAlignment)style.textAlignment;
        paragraphStyle.lineBreakMode = style.lineBreakMode;

        NSDictionary *attributes = @{
            NSFontAttributeName: theFont,
            NSForegroundColorAttributeName: foregroundColor,
            NSParagraphStyleAttributeName: paragraphStyle
        };
        [self drawWithRect:NSRectFromCGRect(rect)
                   options:NSStringDrawingUsesLineFragmentOrigin | NSStringDrawingUsesFontLeading | NSStringDrawingTruncatesLastVisibleLine
                attributes:attributes];
    }
    CPTPopCGContext();
    
    if(currenContextIsNIL)
    {
        [NSGraphicsContext setCurrentContext:nil];
    }
}

**Comment by can16358p** [comment] 2015-09-16 22:19
Having the same here, I think I should go back to old version until this is fixed.

**Comment by Dirk-** [comment] 2015-09-17 09:11
@vrbaski: I tried your code suggestion and it partly worked: Without your code change, I get no text at all, with your code change I get text in the legend, graph title, axis title and annotations, but not for axis labels! Strange...

**Comment by Dirk-** [comment] 2015-09-17 09:41
I added the same code additions to `drawRect` of the `NSAttributedString` category in `CPTPlatformSpecificCategories.m` and now I get text everywhere I want:

```
-(void)drawInRect:(CGRect)rect inContext:(CGContextRef)context
{
    // -------- Addition for OS X 10.11
    BOOL currentContextIsNIL = NO;
    if([NSGraphicsContext currentContext] == nil)
    {
        [NSGraphicsContext setCurrentContext:[NSGraphicsContext graphicsContextWithGraphicsPort:context flipped:NO]];
        currentContextIsNIL = YES;
    }
    // -------- End Addition
    
    CPTPushCGContext(context);

    [self drawWithRect:NSRectFromCGRect(rect)
               options:NSStringDrawingUsesLineFragmentOrigin | NSStringDrawingUsesFontLeading | NSStringDrawingTruncatesLastVisibleLine];

    CPTPopCGContext();
    
    // -------- Addition for OS X 10.11
    if(currentContextIsNIL)
    {
        [NSGraphicsContext setCurrentContext:nil];
    }
    // -------- End Addition
}
```

And it still works in OS X 10.10. Great! Thanks, @vrbaski and, of course, thanks @eskroch et al. for Core Plot!

**Comment by mike-lischke** [comment] 2015-09-17 11:29
I wonder why there is this need to check for the current context first. Does it not work on older OS versions otherwise? There is a context passed in and that should be used for drawing, no? In all cases. And resetting the current context always, also seems reasonable. Other drawing code will exactly do the same like here, namely set a proper drawing context first. Maybe I'm missing something here?

**Comment by eskroch** [comment] 2015-09-18 01:40
The fix needs to be in the `CPTPushCGContext()` and `CPTPopCGContext()` functions. This keeps the context handling code in one place making it easier to maintain in the future.

**Comment by eskroch** [comment] 2015-09-19 23:33
This should be fixed now on both the master and release-2.0 branches. Please test and let me know if it's working. If so, I'll move forward with the 2.0 release.

**Comment by pascalfribi** [comment] 2015-09-20 15:05
Hi,

I have pulled the Xcode 7 branch and tested it on my application. This seems to work fine again! Thanks for this great library! Do you plan to make a small Apple Watch API? :-)

**Comment by eskroch** [comment] 2015-09-20 22:19
Good to hear. I'm thinking about adding watchOS and tvOS frameworks to release 2.1. :-)

**Closed by eskroch** 2015-09-20 22:19 UTC
Labels: Bug, Priority-Medium
