### ISSUE TITLE
Initializing '__strong id<CPTPieChartDelegate>' with an expression of incompatible type 'id<CALayerDelegate> _Nullable'

### ISSUE THREAD

**Issue by djones614** [core-plot/core-plot#290] opened 2016-07-13 04:01 UTC
I'm receiving multiple delegate issues when trying to build.

Line of code: id<CPTPieChartDelegate> theDelegate = self.delegate;
Error: .../CorePlot/framework/Source/CPTPieChart.m:1167:29: Initializing '__strong id<CPTPieChartDelegate>' with an expression of incompatible type 'id<CALayerDelegate> _Nullable'

Line of code: id<CPTBarPlotDelegate> theDelegate = self.delegate;
Error: .../CorePlot/framework/Source/CPTBarPlot.m:1400:28: Initializing '__strong id<CPTBarPlotDelegate>' with an expression of incompatible type 'id<CALayerDelegate> _Nullable'

Line of code: id<CPTPlotDelegate> theDelegate = self.delegate;
Error: .../CorePlot/framework/Source/CPTPlot.m:1898:25: Initializing '__strong id<CPTPlotDelegate>' with an expression of incompatible type 'id<CALayerDelegate> _Nullable'

I'm using:
Xcode 8 beta 2
core-plot-release-2.2

**Comment by eskroch** [comment] 2016-07-13 11:10
Duplicate of issue #284. This is fixed on the `release-2.3` branch.

**Comment by djones614** [comment] 2016-07-13 14:04
Thanks!  Is release-2.3 available?  The latest I'm seeing is release-2.2.

**Comment by eskroch** [comment] 2016-07-13 14:09
No. I don't want to do the 2.3 release until Xcode and the Apple OSs are final in the fall in case there are more changes in future betas. In the meantime, pull the code from the branch.

**Comment by DD-P** [comment] 2016-07-13 19:12
Hi and thank you for Core Plot.  I would like to access these changes on the `release-2.3` branch also.

**Comment by eskroch** [comment] 2016-07-14 01:58
If you're using a dependency manager like CocoaPods or Carthage, just point it at the branch instead of the release. If you're using a pre-built library from the release, you'll need to pull the code from GitHub and build your own.

**Comment by DD-P** [comment] 2016-07-14 06:58
Apologies if I'm missing something, but I can't locate branch `release-2.3`. The only branches I can currently see for this repo are:

- master
- release-2.2
- release-2.1
- release-2.0
- xcode-7
- wasSelectedEvents
- momentumScrolling

**Comment by eskroch** [comment] 2016-07-14 11:16
Sorry, that was a typo. I meant `release-2.2`.

**Comment by djones614** [comment] 2016-07-14 13:11
Typically I download the latest and everything works so I apologize as well for not quite understanding this.  I'm using release-2.2 and I still see this issue.  Since release-2.3 isn't available yet, how can we fix this issue?  Is the fix in master?

**Comment by eskroch** [comment] 2016-07-15 14:48
This is new with Xcode 8 beta 2. I'll fix it today.

**Comment by eskroch** [comment] 2016-07-15 21:12
Fixed on the `release-2.2` branch.

**Closed by eskroch** 2016-07-15 21:12 UTC
Labels: Bug, Priority-Low

**Comment by codemonkies** [comment] 2016-09-11 14:18
you can get the pod with this

pod 'CorePlot', :git => 'https://github.com/core-plot/core-plot.git', :branch => 
'release-2.2’
