### ISSUE TITLE
I updated Xcode to 7.3 and shows me CPTPlot`s 'datasource' is unavailable

### ISSUE THREAD

**Issue by chary1n** [core-plot/core-plot#271] opened 2016-03-29 09:38 UTC
I updated Xcode from 7.2 to 7.3 , my project works well on 7.2,but can not build success any more after i updated to 7.3. 
Details: i create a class 'CPTScatterPlot' extends CPTPlot 
 ` // 
    CPTScatterPlot *baseLinePlot = [[[CPTScatterPlot alloc] init] autorelease];
    //id 
    baseLinePlot. identifier = @"Base Line" ;
      baseLinePlot.dataLineStyle = baseLineStyle;
    baseLinePlot.dataSource = self ;
`
i still build failed and got message: 'dataSource' is unavailable.
it may be something wrong with my config,please tell me how to fix it,thank you very much.

**Comment by eskroch** [comment] 2016-03-29 11:25
Duplicate of issue #269.

**Closed by eskroch** 2016-03-29 11:25 UTC
Labels: Duplicate

**Comment by chary1n** [comment] 2016-04-12 05:35
@eskroch  i have fixed this issue, Xcode - BuildSetting - Weak Reference in Manual Retain Release to Yes and solved. Thank you very much anyway.

**Comment by EvgenyKarkan** [comment] 2016-10-31 11:40
@chary1n thanks - it did the trick.
