### ISSUE TITLE
Build error with 2.2 release

### ISSUE THREAD

**Issue by koenvanderdrift** [core-plot/core-plot#288] opened 2016-06-25 01:27 UTC
I'm getting the following build error on Xcode 7.3.1, using the 2.2 release branch:

`.../core-plot/framework/iPhoneOnly/CPTGraphHostingView.m:233:53: Nullability specifier 'nonnull' conflicts with existing specifier 'nullable'`

The offending line is `-(void)touchesCancelled:(nonnull NSSet<UITouch *> *)touches withEvent:(nullable UIEvent *)event
`

**Comment by koenvanderdrift** [comment] 2016-06-25 01:31
Sorry for the noise, just read in one of the closed issues that release 2.2 only works with Xcode 8.

**Comment by eskroch** [comment] 2016-06-25 10:36
Duplicate of issue #284.

**Closed by eskroch** 2016-06-25 10:36 UTC
Labels: Duplicate

**Comment by guochangxindeGH** [comment] 2017-11-12 06:13
I also encountered the same issue #284.
