### ISSUE TITLE
Implement vertical line track indicator 

### ISSUE THREAD

**Issue by pprraasshhaanntthh** [core-plot/core-plot#244] opened 2015-11-09 02:01 UTC
![bdy5t](https://cloud.githubusercontent.com/assets/4393799/11024397/bcda58d0-86b3-11e5-80ab-eccc103dbd35.jpg)

How can I implement the above ? I couldn't find anything like in the examples

**Comment by eskroch** [comment] 2015-11-09 02:13
We've been discussing an issue like this on the [discussion board](https://groups.google.com/forum/#!topic/coreplot-discuss/8U_WoKAq1-0) recently. That thread includes a sample project that has code that should get you started.

**Comment by eskroch** [comment] 2015-11-12 01:34
Duplicate of issue #241.

**Closed by eskroch** 2015-11-12 01:34 UTC
Labels: Duplicate, Question
